import * as Joi from 'joi';

export const environmentsVariablesValidationSchema = Joi.object({
  APP_URL: Joi.string().required(),
  PORT: Joi.number().default(3000),
  GLOBAL_PREFIX_APP: Joi.string().required(),
  NODE_ENV: Joi.string().required(),
  DATABASE_URL: Joi.string().required(),
  ACCESS_TOKEN_SECRET_USER: Joi.string().required(),
  ACCESS_TOKEN_EXPIRATION_USER: Joi.string().required(),
  REFRESH_TOKEN_SECRET_USER: Joi.string().required(),
  REFRESH_TOKEN_EXPIRATION_USER: Joi.string().required(),
  ACCESS_TOKEN_SECRET_MODER: Joi.string().required(),
  ACCESS_TOKEN_EXPIRATION_MODER: Joi.string().required(),
  REFRESH_TOKEN_SECRET_MODER: Joi.string().required(),
  REFRESH_TOKEN_EXPIRATION_MODER: Joi.string().required(),
  ACCESS_TOKEN_SECRET_ADMIN: Joi.string().required(),
  ACCESS_TOKEN_EXPIRATION_ADMIN: Joi.string().required(),
  REFRESH_TOKEN_SECRET_ADMIN: Joi.string().required(),
  REFRESH_TOKEN_EXPIRATION_ADMIN: Joi.string().required(),
  SWAGGER_TITLE: Joi.string().required(),
  SWAGGER_URL: Joi.string().required(),
  SWAGGER_TAB_TITLE: Joi.string().required(),
  SWAGGER_DESCRIPTION: Joi.string().required(),
  SWAGGER_VERSION: Joi.string().required(),
  SWAGGER_BEARER_AUTH_TYPE: Joi.string().default('http'),
  SWAGGER_BEARER_FORMAT: Joi.string().default('bearer'),
  SWAGGER_BEARER_SCHEME: Joi.string().default('bearer'),
  SWAGGER_BEARER_IN: Joi.string().default('header'),
  SWAGGER_BEARER_NAME: Joi.string().default('JWT-Auth'),
  SWAGGER_BEARER_SECURITY_REQ: Joi.string().default('JWT-Auth'),
});
